version: '3.1'
services:
  backend: 
    build: ./backend-totvs
    container_name: backend_totvs
    ports:
      - 8080:8080
    volumes:
      - uploads:/uploads
  frontend:
    build: ./frontend-totvs
    container_name: frontend_totvs
    ports:
      - 4200:80
    links:
      - backend

volumes:
  uploads: 